name: Build Clash Rules

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Download Clash YAML Sources
        run: |
          mkdir -p tmp
          urls=(
            "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"
            "https://raw.githubusercontent.com/REIJI007/AdBlock_Rule_For_Clash/main/adblock_reject.yaml"
            "https://anti-ad.net/clash.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyPrivacy.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
          )

          for i in "${!urls[@]}"; do
            echo "Downloading ${urls[$i]}"
            curl -sSL --retry 3 "${urls[$i]}" -o tmp/source_$i.yaml
          done

      - name: Merge & Deduplicate Rules
        run: |
          mkdir -p dist
          python3 - <<EOF
import yaml
import glob
from datetime import datetime

sources = glob.glob("tmp/*.yaml")
all_rules = set()

for src in sources:
    with open(src, "r", encoding="utf-8") as f:
        try:
            data = yaml.safe_load(f)
            if isinstance(data, dict):
                for key in ["rules", "payload"]:
                    if key in data and isinstance(data[key], list):
                        for line in data[key]:
                            line = str(line).strip().strip("'\"")
                            if line and not line.startswith("#"):
                                all_rules.add(line)
            elif isinstance(data, list):
                for line in data:
                    line = str(line).strip().strip("'\"")
                    if line and not line.startswith("#"):
                        all_rules.add(line)
        except Exception as e:
            continue

output_file = "dist/merged-clash.yaml"
with open(output_file, "w", encoding="utf-8") as f:
    f.write("# =======================================\n")
    f.write("# Clash Rules - 自动生成\n")
    f.write(f"# 生成时间: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n")
    f.write(f"# 规则总数: {len(all_rules)}\n")
    f.write("# =======================================\n\n")
    for rule in sorted(all_rules):
        f.write(rule + "\n")
EOF

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dist/merged-clash.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Clash rules: $(date -u '+%Y-%m-%d')"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin main
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: clash-rules-$(date -u +'%Y%m%d')
          name: "Clash 规则更新"
          body: "本次规则自动生成更新，总规则数: $(wc -l < dist/merged-clash.yaml)"
          files: |
            dist/merged-clash.yaml

      - name: Show Rules Stats
        run: |
          echo "================= Clash Rules Stats ================="
          total_rules=$(grep -E '^(DOMAIN-SUFFIX|DOMAIN-KEYWORD|DOMAIN|IP-CIDR|IP-CIDR6),' dist/merged-clash.yaml | wc -l)
          echo "Merged total rules: $total_rules"
          head -n 20 dist/merged-clash.yaml
          echo "====================================================="
