name: Build Clash Rules

on:
  schedule:
    - cron: "0 0 * * *"    # 每天 UTC 0 点
    - cron: "0 12 * * *"   # 每天 UTC 12 点
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download & Merge Clash YAML Rules
        run: |
          mkdir -p dist tmp
          urls=(
            "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"
            "https://raw.githubusercontent.com/REIJI007/AdBlock_Rule_For_Clash/main/adblock_reject.yaml"
            "https://anti-ad.net/clash.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyPrivacy.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
          )

          > tmp/merged.yaml
          for url in "${urls[@]}"; do
            echo "# ===== 来源: $url =====" >> tmp/merged.yaml
            curl -sSL --retry 3 "$url" >> tmp/merged.yaml || echo "Failed $url"
            echo "" >> tmp/merged.yaml
          done

          cp tmp/merged.yaml dist/merged-clash.yaml
          echo "RELEASE_TAG=clash-rules-$(date -u +'%Y%m%d')" >> $GITHUB_ENV

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dist/merged-clash.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Clash rules: $(date -u '+%Y-%m-%d')"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin main
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Clash 规则更新"
          body: "本次规则自动生成更新"
          files: |
            dist/merged-clash.yaml

      - name: Show Rules Stats
        run: |
          total_lines=$(wc -l < dist/merged-clash.yaml)
          echo "================= Clash Rules Stats ================="
          echo "Merged total lines: $total_lines"
          head -n 20 dist/merged-clash.yaml
          echo "====================================================="
