name: Update Clash Rules

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 UTC 0 点
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run merge script
        run: powershell -File merge_rules.ps1
        shell: pwsh

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/clash_ad_rules.txt
          git commit -m "Update rules $(Get-Date -Format u)" || echo "No changes"
          git push
